//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaveModule.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tLeaveInutang
    {
        public int Id { get; set; }
        public string EIC { get; set; }
        public System.DateTime DateFrom { get; set; }
        public System.DateTime DateTo { get; set; }
        public int NumDays { get; set; }
        public double EquivalentDays { get; set; }
        public string PostedByEIC { get; set; }
        public System.DateTime DatePosted { get; set; }
        public bool IsActive { get; set; }
    }
}
