//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaveModule.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tleaveRestore
    {
        public int recNo { get; set; }
        public string controlNo { get; set; }
        public Nullable<System.DateTime> datePosted { get; set; }
        public Nullable<System.DateTime> dateFiled { get; set; }
        public string EIC { get; set; }
        public string leaveID { get; set; }
        public Nullable<System.DateTime> periodFrom { get; set; }
        public Nullable<System.DateTime> periodTo { get; set; }
        public Nullable<int> isPosted { get; set; }
        public string restoredByEIC { get; set; }
    }
}
