//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaveModule.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmodUserModuleActivity
    {
        public int recNo { get; set; }
        public string EIC { get; set; }
        public Nullable<int> activityID { get; set; }
        public Nullable<int> modulelD { get; set; }
        public string activityName { get; set; }
        public string actionName { get; set; }
        public Nullable<int> orderID { get; set; }
    }
}
