//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaveModule.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trefHoliday
    {
        public int recNo { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<int> day { get; set; }
        public string remarks { get; set; }
        public Nullable<int> statusID { get; set; }
        public Nullable<System.DateTime> dtStamp { get; set; }
    }
}
