//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaveModule.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vEmpInformation
    {
        public string EIC { get; set; }
        public string designation { get; set; }
        public string subpositionName { get; set; }
        public Nullable<System.DateTime> dateFrom { get; set; }
        public string officeCode { get; set; }
        public string staffingCode { get; set; }
        public string fullnameLast { get; set; }
        public string groupName { get; set; }
        public Nullable<int> sg { get; set; }
        public Nullable<int> step { get; set; }
        public string statusCode { get; set; }
        public Nullable<decimal> rateMonth { get; set; }
        public Nullable<decimal> rateDay { get; set; }
        public string empGroupCode { get; set; }
        public string SchemeCode { get; set; }
        public string fullnameFirst { get; set; }
        public string idNo { get; set; }
        public string officeName { get; set; }
        public long row { get; set; }
        public string statusName { get; set; }
    }
}
