//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaveModule.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vEmployeeCompleteField
    {
        public int recNo { get; set; }
        public string idNo { get; set; }
        public string EIC { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string middleName { get; set; }
        public string extName { get; set; }
        public Nullable<System.DateTime> birthdate { get; set; }
        public string birthplace { get; set; }
        public string fullnameFirst { get; set; }
        public string fullnameLast { get; set; }
        public string userEIC { get; set; }
        public Nullable<System.DateTime> dateEncoded { get; set; }
        public string staffingCode { get; set; }
        public string itemNo { get; set; }
        public Nullable<int> sortTagPlantillia { get; set; }
        public Nullable<int> isFunded { get; set; }
        public Nullable<int> isVacant { get; set; }
        public string positionCode { get; set; }
        public string fullDescription { get; set; }
        public string shortDescription { get; set; }
        public string accronym { get; set; }
        public Nullable<int> sg { get; set; }
        public string positionCodeSub { get; set; }
        public string subPositionName { get; set; }
        public string shortPositionName { get; set; }
        public string accronymSub { get; set; }
        public string statusCode { get; set; }
        public string statusName { get; set; }
        public Nullable<int> groupID { get; set; }
        public Nullable<int> isGovService { get; set; }
        public string officeCode { get; set; }
        public string officeName { get; set; }
        public string accronymOffice { get; set; }
        public string officeServiceRec { get; set; }
        public Nullable<int> sortTagOffice { get; set; }
        public string divisionCode { get; set; }
        public string divisionName { get; set; }
        public string accronymDivision { get; set; }
        public string sectionCode { get; set; }
        public string sectionName { get; set; }
        public string accronymSection { get; set; }
        public string salaryCode { get; set; }
        public Nullable<int> step { get; set; }
        public Nullable<decimal> rateMonth { get; set; }
        public Nullable<decimal> rateDay { get; set; }
        public Nullable<System.DateTime> dateFrom { get; set; }
        public string dateTo { get; set; }
        public string paySchemeCode { get; set; }
        public string sepCause { get; set; }
        public string payGroupCode { get; set; }
        public string groupName { get; set; }
        public Nullable<int> sortTagDivision { get; set; }
        public Nullable<int> sortTagSection { get; set; }
        public string empGroupCode { get; set; }
        public string empGroup { get; set; }
        public Nullable<int> isPlantilla { get; set; }
        public string officeCodeWarm { get; set; }
        public Nullable<int> gender { get; set; }
        public string branch { get; set; }
        public Nullable<int> isActive { get; set; }
        public string DesignationSR { get; set; }
        public string statusNameSR { get; set; }
        public Nullable<decimal> salarySR { get; set; }
        public string SchemeCode { get; set; }
        public string oldItemNo { get; set; }
        public string chargeCode { get; set; }
        public string chargeName { get; set; }
    }
}
