//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaveModule.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vLeaveMasterLedger
    {
        public Nullable<long> Id { get; set; }
        public string DtrID { get; set; }
        public string EIC { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Month { get; set; }
        public string Remarks { get; set; }
        public Nullable<double> VLBalance { get; set; }
        public Nullable<double> SLBalance { get; set; }
    }
}
